### ISSUE TITLE
Edit Application Not Working - Something went wrong

### ISSUE THREAD

**Issue by jayrajmulani** [jayrajmulani/se-group1-project2#1]
![image](https://user-images.githubusercontent.com/39649967/204413698-dfb6aa14-e30d-420f-bc0a-b41b92b0e97a.png)

@Dhrumil0310 could you take a look?

**Comment by Dhrumil0310** [comment]
Upon debugging, I found that in the API `/update_application`, `session[email]` is used. However, the session object is none. @jayrajmulani Can you take a look as well? 

I think this should resolve the issue.

**Comment by jayrajmulani** [comment]
Yes, good catch. Please create a new branch. Also check for other APIs. I suspect similar issues in other APIs as well.

**Comment by Dhrumil0310** [comment]
Yes, found another issue in the delete API call. It was being referenced via the old `/api` proxy. Updated it to fetch the base URL from the config file
