### ISSUE TITLE
Create new workflow diagrams and videos

### ISSUE THREAD

**Issue by jayrajmulani** [jayrajmulani/se-group1-project2#27]

**Comment by Dhrumil0310** [comment]
![Block](https://user-images.githubusercontent.com/50771715/205509076-797a0070-a63d-4930-aaed-bc152ce64d65.jpg)
@jayrajmulani Can you please check this workflow diagram and let me know if any chances are required?

**Comment by jayrajmulani** [comment]
I guess the profile page is missing.. Also, Now that the tool has many features, we can separate out the workflow diagram and column details. Whatever is comfortable. 

Instead of showing all the fields in this diagram, we can have a separate ER like diagram.

https://github.com/jayrajmulani/edu-setu/blob/main/assets/Relational_Diagram.png

Something like this.. Also,  If you are doing it on draw.io, do share the link for that as well.

**Comment by Dhrumil0310** [comment]
Intro video: https://app.animaker.com/video/13G8NDYJQLOO6FS1
Draw.io: https://drive.google.com/file/d/1yYgg7NbaOTWMnkHFSETqwURgmRcs2Lbb/view?usp=sharing Restricted access to members

**Comment by jayrajmulani** [comment]
https://user-images.githubusercontent.com/39649967/205716460-d45bbad7-6222-4a0d-9bb1-bbd808db53a2.mp4
