### ISSUE TITLE
Issue with adding saved job applications

### ISSUE THREAD

**Issue by Dhrumil0310** [jayrajmulani/se-group1-project2#3]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/50771715/204425971-6f955568-ec38-45c6-9f0b-82c18aa7d637.png">
<img width="920" alt="image" src="https://user-images.githubusercontent.com/50771715/204426149-c15bda7c-544d-4a87-a185-ba9b965aa008.png">
@Yashasya Can you please check what's going wrong here?

**Comment by Yashasya** [comment]
After debugging, I learned that the API request is the same for saved jobs and My Applications. I have made some changes in the API and made the description and date fields optional. @Dhrumil0310 I have checked these changes in my local system and it's working properly
