### ISSUE TITLE
Should we remove the Profile Functionality temporaily?

### ISSUE THREAD

**Issue by Yashasya** [jayrajmulani/se-group1-project2#36]
Manually creating the profile and viewing it only for oneself doesn't make much sense. Can we remove that feature altogether? Can we have it as a future scope as a mock ATS so that users can see how their resume performs and auto-parse the profile? 
 
Any suggestions @jayrajmulani ?

**Comment by jayrajmulani** [comment]
Yes. I think it makes sense. We are already adding a couple of major features. Go ahead.

**Comment by Yashasya** [comment]
I have not completely removed the code, just commented the UI and backend pieces.

**Comment by jayrajmulani** [comment]
Hey @Yashasya, removing the profile compont is leading to ui tests failing that checks if profile component was rendered or not? Can you explore the UI tests and remove tests for profile and add tests for the components that we added?

https://github.com/jayrajmulani/se-group1-project2/blob/main/ui/__tests__/App.test.jsx#L185

Here is the test..

**Comment by jayrajmulani** [comment]
Also,  please check the style in the app.py. https://github.com/jayrajmulani/se-group1-project2/blob/main/backend/app.py#L85

Style checker has identified some issue, likely due to this comment here.

**Comment by jayrajmulani** [comment]
Issue fixed by #44
