### ISSUE TITLE
Auto Documentation

### ISSUE THREAD

**Issue by jayrajmulani** [jayrajmulani/se-group1-project2#8]
The original team members mentioned that they lost some marks related to auto documetation. Lets make sure we dont face the same

**Comment by anishasc99** [comment]
Merge #13 failed, likely due to protected main branch. @jayrajmulani can you check?

**Comment by anishasc99** [comment]
Worked after fixing previous error. Closing this issue.

**Comment by jayrajmulani** [comment]
I have disabled the branch rules. Can you try?

**Comment by jayrajmulani** [comment]
Cool
