### ISSUE TITLE
Update readme badges github repo (if applicable)

### ISSUE THREAD

**Issue by jayrajmulani** [jayrajmulani/se-group1-project2#9]

**Comment by Yashasya** [comment]
I Have updated all the badges but somehow code coverage and UI Build is not working properly. Can you please have a look @jayrajmulani

**Comment by jayrajmulani** [comment]
Hey @Yashasya , I saw you uncommented the code for codecov. Still, if we check the logs, there is an error related to some missing token. Can you please look into this issue, @anishasc99 ?

**Comment by anishasc99** [comment]
Fixed by changing codecov path to read percentage.
